---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
