---
- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes # Good practice if unit files might have changed

- name: reload prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: restart grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes
