---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: restart mysqld_exporter
  systemd:
    name: mysqld_exporter
    state: restarted
