---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes # Good practice to include if unit files might have changed

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
