---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Configure nginx main settings
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: true
  notify: restart nginx

- name: Create load balancer configuration
  template:
    src: loadbalancer.conf.j2
    dest: /etc/nginx/sites-available/loadbalancer
    backup: true
  notify: restart nginx

- name: Enable load balancer site
  file:
    src: /etc/nginx/sites-available/loadbalancer
    dest: /etc/nginx/sites-enabled/loadbalancer
    state: link
  notify: restart nginx

- name: Create nginx log directory
  file:
    path: /var/log/nginx
    state: directory
    owner: www-data
    group: adm
    mode: '0755'

- name: Test nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true
