---
# Check if monitoring tools are already installed
- name: Check if Prometheus is installed (Ubuntu package)
  command: prometheus --version
  register: prometheus_installed
  failed_when: false
  changed_when: false

- name: Check if Grafana is installed
  command: grafana-server -v
  register: grafana_installed
  failed_when: false
  changed_when: false

- name: Display monitoring tools status
  debug:
    msg: 
      - "Prometheus is {{ 'already installed' if prometheus_installed.rc == 0 else 'not installed' }}"
      - "Grafana is {{ 'already installed' if grafana_installed.rc == 0 else 'not installed' }}"

# Install Prometheus using Ubuntu packages (the method that works)
- name: Update package cache
  apt:
    update_cache: true
  when: prometheus_installed.rc != 0

- name: Install Prometheus from Ubuntu packages (reliable method)
  apt:
    name: prometheus
    state: present
    install_recommends: false
  when: prometheus_installed.rc != 0
  register: prometheus_install_result

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
  when: prometheus_installed.rc != 0 and prometheus_install_result is succeeded

# Install Grafana using the method that works
- name: Install prerequisites for Grafana
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  when: grafana_installed.rc != 0

- name: Add Grafana GPG key (manual method that works)
  shell: curl -fsSL https://apt.grafana.com/gpg.key | apt-key add -
  when: grafana_installed.rc != 0
  ignore_errors: true

- name: Add Grafana repository (manual method that works)
  shell: echo 'deb https://apt.grafana.com stable main' > /etc/apt/sources.list.d/grafana.list
  when: grafana_installed.rc != 0
  ignore_errors: true

- name: Update package cache for Grafana
  apt:
    update_cache: true
  when: grafana_installed.rc != 0
  ignore_errors: true

- name: Install Grafana (the method that works)
  apt:
    name: grafana
    state: present
  when: grafana_installed.rc != 0
  register: grafana_install_result
  ignore_errors: true

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true
    daemon_reload: true
  when: grafana_installed.rc != 0 and grafana_install_result is succeeded

- name: Display monitoring installation results
  debug:
    msg:
      - "Monitoring setup complete:"
      - "Prometheus: {{ 'Running' if prometheus_installed.rc == 0 or (prometheus_install_result is defined and prometheus_install_result is succeeded) else 'Failed to install' }}"
      - "Grafana: {{ 'Running' if grafana_installed.rc == 0 or (grafana_install_result is defined and grafana_install_result is succeeded) else 'Failed to install' }}"
      - "Access URLs:"
      - "  - Prometheus: http://localhost:9090"
      - "  - Grafana: http://localhost:3000 (admin/admin)"
